// tests/film/camera.cpp — verifies the ported camera (film Camera.hpp).
//
// A shot carries a FRAMING (how close) and a CAMERA MOVE (what it does while it is on). Between them
// they decide the zoom, where the frame points, the roll, and how black the cut is. Like the palette,
// this is arithmetic that has to agree with the browser exactly -- a native render that pushes in at a
// different rate is a different film -- so the ground truth is 200 cases generated by the browser's
// own framingFor() and fadeAmount() across every shot of a real film at five points through each.
#include "maz/film/Camera.hpp"
#include "maz/io/Json.hpp"

#include <cmath>
#include <cstdio>
#include <string>

static int g_fail = 0;
#define CHECK(c, m) do{ if(!(c)){ std::printf("FAIL: %s\n",(m)); ++g_fail; } }while(0)

int main(int argc, char** argv) {
    const std::string reelPath = argc > 1 ? argv[1] : "tests/film/reel-fixture.json";
    const std::string camPath = argc > 2 ? argv[2] : "tests/film/camera-fixture.json";

    const maz::film::Reel reel = maz::film::loadReel(reelPath);
    if (!reel.valid) {
        std::printf("FAIL: could not load the reel (%s)\n", reel.error.c_str());
        return 1;
    }
    std::string text;
    if (!maz::io::readTextFile(camPath, text)) {
        std::printf("FAIL: could not read the camera fixture at %s\n", camPath.c_str());
        return 1;
    }
    const maz::io::JsonParseResult doc = maz::io::parseJson(text);
    CHECK(doc.ok, "the camera fixture is valid JSON");

    const maz::io::JsonValue& cases = doc.value["cases"];
    CHECK(cases.isArray() && cases.size() == 200u, "the fixture carries all 200 camera cases");

    int wrong = 0;
    double worst = 0.0;
    std::string firstBad;
    for (const maz::io::JsonValue& c : cases.items()) {
        const std::size_t i = static_cast<std::size_t>(c["index"].asInt(0));
        const double progress = c["progress"].asNumber(0.0);
        const double time = c["time"].asNumber(0.0);
        const maz::film::Shot& shot = reel.shots[i];
        const maz::film::CameraShot cam = maz::film::cameraFor(shot, progress, time);
        const double fade = maz::film::fadeAt(reel, shot, time);

        const double d = std::fmax(
            std::fmax(std::fabs(cam.zoom - c["zoom"].asNumber()),
                      std::fabs(cam.panX - c["panX"].asNumber())),
            std::fmax(std::fmax(std::fabs(cam.panY - c["panY"].asNumber()),
                                std::fabs(cam.panYMove - c["panYMove"].asNumber())),
                      std::fmax(std::fabs(cam.roll - c["roll"].asNumber()),
                                std::fabs(fade - c["fade"].asNumber()))));
        worst = std::fmax(worst, d);
        if (d > 1e-9) {
            ++wrong;
            if (firstBad.empty()) {
                firstBad = "shot " + std::to_string(i) + " (" + shot.framing + "/" + shot.camera +
                           ") at progress " + std::to_string(progress) + " off by " +
                           std::to_string(d);
            }
        }
    }
    if (wrong != 0) {
        std::printf("FAIL: %d of %zu camera cases differ from the browser; first: %s\n", wrong,
                    cases.size(), firstBad.c_str());
        ++g_fail;
    }

    // --- The properties behind the numbers, asserted directly. ---
    {
        // A close-up really is closer than a wide shot.
        maz::film::Shot wide;
        wide.framing = "wide";
        wide.camera = "static";
        maz::film::Shot close = wide;
        close.framing = "close";
        CHECK(maz::film::cameraFor(close, 0.0, 0.0).zoom > maz::film::cameraFor(wide, 0.0, 0.0).zoom,
              "a close-up is closer than a wide shot");
    }
    {
        // A push moves in over the shot; a pull moves out.
        maz::film::Shot s;
        s.framing = "wide";
        s.camera = "push";
        CHECK(maz::film::cameraFor(s, 1.0, 0.0).zoom > maz::film::cameraFor(s, 0.0, 0.0).zoom,
              "a push ends closer than it starts");
        s.camera = "pull";
        CHECK(maz::film::cameraFor(s, 1.0, 0.0).zoom < maz::film::cameraFor(s, 0.0, 0.0).zoom,
              "a pull ends wider than it starts");
    }
    {
        // Nothing is ever perfectly still, and nothing ever inverts or vanishes.
        bool sane = true;
        const char* framings[] = {"wide", "mid", "close", "two", "ots", "insert", "low"};
        const char* moves[] = {"static", "push", "push-slow", "pull",  "pan-l",
                               "pan-r",  "track-l", "track-r", "handheld", "whip"};
        for (const char* f : framings) {
            for (const char* m : moves) {
                for (int k = 0; k <= 20; ++k) {
                    maz::film::Shot s;
                    s.framing = f;
                    s.camera = m;
                    s.mood = static_cast<double>(k) / 20.0;
                    const double pr = static_cast<double>(k) / 20.0;
                    const maz::film::CameraShot cam = maz::film::cameraFor(s, pr, pr * 3.0);
                    if (!(cam.zoom > 0.5) || cam.zoom > 4.0 || std::fabs(cam.panX) > 0.5 ||
                        std::fabs(cam.roll) > 0.1 || !std::isfinite(cam.panYMove)) {
                        sane = false;
                    }
                }
            }
        }
        CHECK(sane, "every framing and move stays inside sane zoom, pan and roll bounds");
    }
    {
        // Handheld shakes on the FILM clock, so two shots of different lengths shake at one speed.
        maz::film::Shot s;
        s.framing = "wide";
        s.camera = "handheld";
        s.mood = 0.8;
        const double a = maz::film::cameraFor(s, 0.5, 10.0).panX;
        const double b = maz::film::cameraFor(s, 0.9, 10.0).panX;
        CHECK(std::fabs(a - b) < 1e-9,
              "handheld shake depends on the film clock, not on progress through the shot");
        CHECK(std::fabs(maz::film::cameraFor(s, 0.5, 11.0).panX - a) > 1e-6,
              "handheld shake does move with the film clock");
    }
    {
        // Roll only where the story has come apart.
        maz::film::Shot calm;
        calm.framing = "wide";
        calm.camera = "static";
        calm.mood = 0.5;
        maz::film::Shot crisis = calm;
        crisis.mood = 0.95;
        CHECK(maz::film::cameraFor(calm, 0.5, 0.0).roll == 0.0, "a calm scene does not tilt");
        CHECK(maz::film::cameraFor(crisis, 0.5, 0.0).roll > 0.0, "a scene in crisis tilts");
    }
    {
        // The film starts and ends black, and dips between scenes but not inside one.
        CHECK(std::fabs(maz::film::fadeAt(reel, reel.shots[0], 0.0) - 1.0) < 1e-9,
              "the film starts black");
        CHECK(maz::film::fadeAt(reel, reel.shots.back(), reel.duration - 0.001) > 0.99,
              "the film ends black");
        CHECK(maz::film::fadeAt(reel, reel.shots[3], reel.shots[3].start + reel.shots[3].duration * 0.5) < 0.01,
              "the middle of a shot is not faded");
    }

    if (g_fail == 0) {
        std::printf("film camera: all checks passed (%zu cases matched the browser to %.2g)\n",
                    cases.size(), worst);
    }
    return g_fail == 0 ? 0 : 1;
}
