// tests/film/dress.cpp — the set dressing, the faces and the held objects, against the browser.
//
// Three things arrived in the browser renderer and not in the engine's, and the gap was invisible in
// every test: a native frame and a browser frame of the same instant simply differed at the edges of
// the picture and nobody could say by how much or why. These are the ports, and this is what keeps
// them ports rather than second designs.
//
// The fixture (tests/film/dress-fixture.json) is generated by running film/js/set-dress.js and
// film/js/film-figures.js in Node. Everything is demanded to agree exactly, or to 1e-12 where a double
// is involved, because a room the browser dresses as abandoned and the engine dresses as kept is not
// the same film rendered twice.
#include "maz/film/Face.hpp"
#include "maz/film/SetDress.hpp"
#include "maz/io/Json.hpp"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>

namespace {

int g_fail = 0;
#define CHECK(c, m) do{ if(!(c)){ std::printf("FAIL: %s\n", std::string(m).c_str()); ++g_fail; } }while(0)

std::string readAll(const std::string& path) {
    std::ifstream f(path);
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

std::string shapeName(maz::film::HeldShape s) {
    switch (s) {
        case maz::film::HeldShape::Long: return "long";
        case maz::film::HeldShape::Flat: return "flat";
        case maz::film::HeldShape::Round: return "round";
        case maz::film::HeldShape::Box: return "box";
    }
    return "box";
}

} // namespace

int main(int argc, char** argv) {
    const std::string path = argc > 1 ? argv[1] : "tests/film/dress-fixture.json";
    const std::string text = readAll(path);
    if (text.empty()) {
        std::printf("FAIL: could not read the fixture at %s\n", path.c_str());
        return 1;
    }
    const maz::io::JsonParseResult parsed = maz::io::parseJson(text);
    const maz::io::JsonValue& doc = parsed.value;
    if (!doc.isObject()) {
        std::printf("FAIL: the fixture at %s is not JSON\n", path.c_str());
        return 1;
    }

    const double kTol = 1e-12;

    // --- 1. Every dressing of every set in every genre, against the browser. ---
    {
        int checked = 0;
        double worst = 0.0;
        std::string worstWhere;
        int wrongCondition = 0;
        int wrongCount = 0;
        std::string firstWrong;

        for (const auto& c : doc["dress"].items()) {
            const std::string setKey = c["set"].asString();
            const std::string genre = c["genre"].asString();
            const auto seed = static_cast<std::uint32_t>(c["seed"].asNumber());
            const maz::io::JsonValue& want = c["d"];
            const maz::film::Dressing got = maz::film::dressingFor(setKey, genre, seed);
            const std::string where = setKey + "/" + genre + "/" + std::to_string(seed);
            ++checked;

            if (maz::film::conditionName(got.condition) != want["condition"].asString()) {
                ++wrongCondition;
                if (firstWrong.empty()) {
                    firstWrong = where + ": engine says " +
                                 maz::film::conditionName(got.condition) + ", browser says " +
                                 want["condition"].asString();
                }
            }

            const auto& wantProps = want["props"].items();
            const auto& wantMarks = want["marks"].items();
            if (got.props.size() != wantProps.size() || got.marks.size() != wantMarks.size()) {
                ++wrongCount;
                if (firstWrong.empty()) {
                    firstWrong = where + ": " + std::to_string(got.props.size()) + " props and " +
                                 std::to_string(got.marks.size()) + " marks against " +
                                 std::to_string(wantProps.size()) + " and " +
                                 std::to_string(wantMarks.size());
                }
                continue;
            }

            auto note = [&](double diff, const std::string& what) {
                if (diff > worst) { worst = diff; worstWhere = where + " " + what; }
            };
            for (std::size_t i = 0; i < got.props.size(); ++i) {
                const maz::io::JsonValue& w = wantProps[i];
                CHECK(maz::film::propName(got.props[i].kind) == w["kind"].asString(),
                      where + " prop " + std::to_string(i) + ": engine drew a " +
                      maz::film::propName(got.props[i].kind) + ", browser drew a " +
                      w["kind"].asString());
                note(std::fabs(got.props[i].x - w["x"].asNumber()), "prop x");
                note(std::fabs(got.props[i].y - w["y"].asNumber()), "prop y");
                note(std::fabs(got.props[i].w - w["w"].asNumber()), "prop w");
                note(std::fabs(got.props[i].h - w["h"].asNumber()), "prop h");
            }
            for (std::size_t i = 0; i < got.marks.size(); ++i) {
                const maz::io::JsonValue& w = wantMarks[i];
                note(std::fabs(got.marks[i].x - w["x"].asNumber()), "mark x");
                note(std::fabs(got.marks[i].y - w["y"].asNumber()), "mark y");
                note(std::fabs(got.marks[i].alpha - w["alpha"].asNumber()), "mark alpha");
            }
            const bool wantLamp = want["lamp"].isObject();
            CHECK(got.lamp.lit == wantLamp,
                  where + ": the lamp is " + (got.lamp.lit ? "lit" : "out") + " here and " +
                  (wantLamp ? "lit" : "out") + " in the browser");
            if (got.lamp.lit && wantLamp) {
                note(std::fabs(got.lamp.x - want["lamp"]["x"].asNumber()), "lamp x");
                note(std::fabs(got.lamp.r - want["lamp"]["r"].asNumber()), "lamp r");
            }
        }

        CHECK(wrongCondition == 0, std::to_string(wrongCondition) +
              " rooms are in a different condition from the browser's; first: " + firstWrong);
        CHECK(wrongCount == 0, std::to_string(wrongCount) +
              " rooms hold a different number of things; first: " + firstWrong);
        char message[256];
        std::snprintf(message, sizeof(message),
                      "every prop and mark is where the browser puts it (worst %.3g at %s, over %d)",
                      worst, worstWhere.c_str(), checked);
        CHECK(worst < kTol, message);
        CHECK(checked >= 700, "the fixture is too small to have proved anything");
    }

    // --- 2. Dressing never lands where the actors stand. ---
    //
    // The rule that lets one layer be switched on for all fifteen sets without looking at all fifteen.
    // A prop's box is a promise: x leaves room for w. Break it and a crate placed inside the left band
    // reaches past x=200 and grows out of somebody's chest.
    {
        const char* sets[] = {"ward", "room", "kitchen", "corridor", "office", "bar", "ship",
                              "chapel", "industrial", "vehicle", "lighthouse",
                              "woods", "street", "field", "water"};
        const char* genres[] = {"drama", "thriller", "horror", "comedy", "romance",
                                "scifi", "mystery", "fantasy", "heist", "western"};
        int checked = 0;
        bool intrudes = false;
        std::string where;
        for (const char* setKey : sets) {
            for (const char* genre : genres) {
                for (std::uint32_t seed = 0; seed < 12; ++seed) {
                    const maz::film::Dressing d = maz::film::dressingFor(setKey, genre, seed);
                    auto check = [&](double x, double w, const char* what) {
                        ++checked;
                        const double right = x + w;
                        if (x < 0.0 || right > maz::film::kStageW ||
                            (right > maz::film::kDressLeftHi && x < maz::film::kDressRightLo)) {
                            intrudes = true;
                            if (where.empty()) {
                                where = std::string(setKey) + "/" + genre + "/" +
                                        std::to_string(seed) + " " + what + " at " +
                                        std::to_string(x) + ".." + std::to_string(right);
                            }
                        }
                    };
                    for (const maz::film::Prop& p : d.props) check(p.x, p.w, "prop");
                    for (const maz::film::Mark& m : d.marks) check(m.x, m.w, "mark");
                }
            }
        }
        CHECK(!intrudes, "dressing landed in the acting area: " + where);
        CHECK(checked > 500, "barely anything was dressed: " + std::to_string(checked));
    }

    // --- 3. A crate in a field is a mistake, not a mood. ---
    {
        for (const char* setKey : {"woods", "street", "field", "water"}) {
            for (std::uint32_t seed = 0; seed < 40; ++seed) {
                const maz::film::Dressing d = maz::film::dressingFor(setKey, "drama", seed);
                CHECK(d.marks.empty(), std::string("damp on a wall outdoors, in ") + setKey);
                CHECK(!d.lamp.lit, std::string("a table lamp outdoors, in ") + setKey);
                for (const maz::film::Prop& p : d.props) {
                    const bool outdoorKind = p.kind == maz::film::PropKind::Post ||
                                             p.kind == maz::film::PropKind::Rock ||
                                             p.kind == maz::film::PropKind::Scrub ||
                                             p.kind == maz::film::PropKind::Plank;
                    CHECK(outdoorKind, std::string("a ") + maz::film::propName(p.kind) +
                                       " turned up outdoors in " + setKey);
                }
            }
        }
    }

    // --- 4. The head and the hands land where the browser's do. ---
    //
    // These are doubles on purpose. math::vec2 is float, and taking the same arithmetic through float
    // loses agreement at the seventh decimal -- invisible in a drawn frame, and fatal to a test whose
    // whole job is to prove the port is a port. The same trap as the hour table in Palette.hpp.
    {
        double worst = 0.0;
        std::string where;
        int checked = 0;
        for (const auto& c : doc["joints"].items()) {
            const maz::film::Pose* pose = maz::film::poseNamed(c["pose"].asString());
            if (pose == nullptr) {
                CHECK(false, "the fixture names a pose the engine does not have: " + c["pose"].asString());
                continue;
            }
            const double h = c["h"].asNumber();
            const maz::film::Joints got = maz::film::jointsOf(h, *pose);
            auto note = [&](double a, double b, const char* what) {
                ++checked;
                const double diff = std::fabs(a - b);
                if (diff > worst) {
                    worst = diff;
                    where = c["pose"].asString() + "@" + std::to_string(h) + " " + what;
                }
            };
            note(got.headX, c["head"][static_cast<std::size_t>(0)].asNumber(), "head x");
            note(got.headY, c["head"][static_cast<std::size_t>(1)].asNumber(), "head y");
            note(got.headRx, c["head"][static_cast<std::size_t>(2)].asNumber(), "head rx");
            note(got.headRy, c["head"][static_cast<std::size_t>(3)].asNumber(), "head ry");
            note(got.handLX, c["handL"][static_cast<std::size_t>(0)].asNumber(), "hand L x");
            note(got.handLY, c["handL"][static_cast<std::size_t>(1)].asNumber(), "hand L y");
            note(got.handRX, c["handR"][static_cast<std::size_t>(0)].asNumber(), "hand R x");
            note(got.handRY, c["handR"][static_cast<std::size_t>(1)].asNumber(), "hand R y");
        }
        char message[220];
        std::snprintf(message, sizeof(message),
                      "the head and hands land where the browser puts them (worst %.3g at %s, over %d)",
                      worst, where.c_str(), checked);
        CHECK(worst < kTol, message);
        CHECK(checked > 300, "too few joints to have proved anything");
    }

    // --- 5. Blinks: the same eyes shut at the same moments. ---
    //
    // Two silhouettes blinking in lockstep is the most obvious tell that they are the same puppet
    // twice, so the phase comes off each figure's own name. If the engine's phase differs from the
    // browser's, the two renderers blink at different times and the film is not the same film.
    {
        for (const auto& c : doc["blinks"].items()) {
            const auto seed = static_cast<std::uint32_t>(c["seed"].asNumber());
            int shut = 0;
            double first = -1.0;
            for (int i = 0; i < 40000; ++i) {
                const double t = static_cast<double>(i) * 0.01;
                if (maz::film::blinkAt(t, seed)) {
                    ++shut;
                    if (first < 0.0) first = t;
                }
            }
            CHECK(shut == static_cast<int>(c["shut"].asNumber()),
                  "seed " + std::to_string(seed) + " blinks " + std::to_string(shut) +
                  " times against the browser's " + std::to_string(static_cast<int>(c["shut"].asNumber())));
            CHECK(std::fabs(first - c["first"].asNumber()) < 1e-9,
                  "seed " + std::to_string(seed) + " first blinks at " + std::to_string(first) +
                  " against the browser's " + std::to_string(c["first"].asNumber()));
        }
    }

    // --- 6. A held thing is shaped like the thing it is. ---
    {
        for (const auto& c : doc["held"].items()) {
            const std::string got = shapeName(maz::film::heldShapeFor(c["object"].asString()));
            CHECK(got == c["shape"].asString(),
                  "a " + c["object"].asString() + " is " + got + " here and " +
                  c["shape"].asString() + " in the browser");
        }
    }

    // --- 7. The face gate is the same number on both sides. ---
    {
        CHECK(std::fabs(maz::film::kFaceMinHead - doc["faceMinHead"].asNumber()) < 1e-12,
              "the engine draws a face on a smaller head than the browser does");
    }

    if (g_fail == 0) {
        std::printf("film dress: all checks passed (%zu dressings, %zu joint sets, matched exactly)\n",
                    doc["dress"].items().size(), doc["joints"].items().size());
    }
    return g_fail == 0 ? 0 : 1;
}
