// tests/film/motion.cpp — the engine's character motion, against the browser's own numbers.
//
// A pose is a shape and a performance is a shape that moves, and the port took only the first. The
// native renderer drew people who were physically correct and completely still: never breathing,
// never looking at whoever they were talking to, snapping to a new shape at every cut.
//
// Everything here is checked against a fixture generated by running film/js/film-figures.js in Node
// (tests/film/motion-fixture.json), because AGREE WITH THE BROWSER is the rule the whole port lives
// by. A renderer whose people move differently is not a second renderer of the same film. "Close
// enough" is not the standard: these are the same arithmetic in two languages, so they are demanded
// to agree to 1e-12, and the two places where that is not automatic -- JS `%` on a double, and
// Math.round being floor(x + 0.5) -- are the two places the port could have silently drifted.
#include "maz/film/Motion.hpp"
#include "maz/io/Json.hpp"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

int g_fail = 0;
#define CHECK(c, m) do{ if(!(c)){ std::printf("FAIL: %s\n", std::string(m).c_str()); ++g_fail; } }while(0)

using maz::film::Pose;

// The ten joints, in the fixture's order.
double jointOf(const Pose& p, const std::string& name) {
    if (name == "head") return p.head;
    if (name == "torso") return p.torso;
    if (name == "armL") return p.armL;
    if (name == "foreL") return p.foreL;
    if (name == "armR") return p.armR;
    if (name == "foreR") return p.foreR;
    if (name == "legL") return p.legL;
    if (name == "shinL") return p.shinL;
    if (name == "legR") return p.legR;
    if (name == "shinR") return p.shinR;
    return 0.0;
}

std::string readAll(const std::string& path) {
    std::ifstream f(path);
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

} // namespace

int main(int argc, char** argv) {
    const std::string path = argc > 1 ? argv[1] : "tests/film/motion-fixture.json";
    const std::string text = readAll(path);
    if (text.empty()) {
        std::printf("FAIL: could not read the fixture at %s\n", path.c_str());
        return 1;
    }
    const maz::io::JsonParseResult parsed = maz::io::parseJson(text);
    const maz::io::JsonValue& doc = parsed.value;
    if (!doc.isObject()) {
        std::printf("FAIL: the fixture at %s is not JSON\n", path.c_str());
        return 1;
    }

    std::vector<std::string> joints;
    for (const auto& j : doc["joints"].items()) {
        joints.push_back(j.asString());
    }
    CHECK(joints.size() == 10, "the fixture does not describe ten joints");

    const double kTolerance = 1e-12;

    // --- 1. Every motion function, against the browser, joint for joint. ---
    {
        int checked = 0;
        double worst = 0.0;
        std::string worstWhere;
        for (const auto& c : doc["cases"].items()) {
            const std::string fn = c["fn"].asString();
            const Pose* base = maz::film::poseNamed(c["pose"].asString());
            if (base == nullptr) {
                CHECK(false, "the fixture names a pose the engine does not have: " + c["pose"].asString());
                continue;
            }
            Pose got;
            if (fn == "alive") {
                got = maz::film::aliveAt(*base, c["a"].asNumber(),
                                         static_cast<std::uint32_t>(c["b"].asNumber()));
            } else if (fn == "gaze") {
                got = maz::film::gazeAt(*base, c["a"].asNumber(), c["b"].asNumber(), c["c"].asNumber());
            } else if (fn == "walk") {
                got = maz::film::walkAt(*base, c["a"].asNumber());
            } else if (fn == "gesture") {
                got = maz::film::gestureAt(*base, c["a"].asNumber());
            } else if (fn == "blend") {
                const Pose* second = maz::film::poseNamed(c["pose2"].asString());
                if (second == nullptr) {
                    CHECK(false, "the fixture names a pose the engine does not have: " + c["pose2"].asString());
                    continue;
                }
                got = maz::film::blendPoses(*base, *second, c["a"].asNumber());
            } else {
                CHECK(false, "the fixture asks for a function the engine does not have: " + fn);
                continue;
            }

            const auto& want = c["out"].items();
            for (std::size_t i = 0; i < joints.size() && i < want.size(); ++i) {
                const double diff = std::fabs(jointOf(got, joints[i]) - want[i].asNumber());
                ++checked;
                if (diff > worst) {
                    worst = diff;
                    worstWhere = fn + "/" + c["pose"].asString() + "/" + joints[i];
                }
            }
        }
        char message[256];
        std::snprintf(message, sizeof(message),
                      "every joint of every motion matches the browser (worst %.3g at %s, over %d)",
                      worst, worstWhere.c_str(), checked);
        CHECK(worst < kTolerance, message);
        CHECK(checked > 4000, "the fixture is too small to have proved anything");
    }

    // --- 2. The pose chooser, which was a different rule entirely. ---
    //
    // The native renderer picked from hash(name + beat) + seed: a reasonable rule, and not the
    // browser's, so the two renderers put the same character in different shapes in the same shot.
    {
        int wrong = 0;
        std::string first;
        int checked = 0;
        for (const auto& c : doc["chosen"].items()) {
            ++checked;
            const std::string got = maz::film::poseNameFor(
                c["beat"].asString(), c["tension"].asNumber(), c["speaker"].asBool(),
                static_cast<std::uint32_t>(c["seed"].asNumber()));
            if (got != c["name"].asString()) {
                ++wrong;
                if (first.empty()) {
                    first = c["beat"].asString() + " @" + std::to_string(c["tension"].asNumber()) +
                            ": engine says " + got + ", browser says " + c["name"].asString();
                }
            }
        }
        CHECK(wrong == 0, "the pose chooser disagrees with the browser in " + std::to_string(wrong) +
                          " of " + std::to_string(checked) + " cases; first: " + first);
        CHECK(checked > 400, "too few pose choices to have proved anything");
    }

    // --- 3. A speaker never turns away, whatever the dice say. ---
    {
        bool turned = false;
        for (int seed = 0; seed < 500; ++seed) {
            for (const char* beat : {"spark", "turn"}) {
                for (double tension = 0.0; tension <= 1.0; tension += 0.25) {
                    if (maz::film::poseNameFor(beat, tension, true,
                                               static_cast<std::uint32_t>(seed)) == "turn-away") {
                        turned = true;
                    }
                }
            }
        }
        CHECK(!turned, "somebody turned their back while they were the one talking");
    }

    // --- 4. Motion can never leave the body's limits. ---
    //
    // Each function clamps on the way out, and the reason is that the two ends of a blend are each
    // inside the limits while the straight line between two angles is not always inside anything.
    {
        bool escaped = false;
        std::string where;
        for (const auto& name : maz::film::poseNames()) {
            const Pose* p = maz::film::poseNamed(name);
            for (int step = 0; step <= 40; ++step) {
                const double t = static_cast<double>(step) / 40.0;
                const Pose tries[5] = {
                    maz::film::aliveAt(*p, t * 30.0, static_cast<std::uint32_t>(step * 7919)),
                    maz::film::gazeAt(*p, 0.0, (t - 0.5) * 4000.0, 1.0),
                    maz::film::walkAt(*p, t),
                    maz::film::gestureAt(*p, t),
                    maz::film::blendPoses(*p, *maz::film::poseNamed("head-in-hands"), t)
                };
                for (const Pose& candidate : tries) {
                    if (!maz::film::withinLimits(candidate)) {
                        escaped = true;
                        if (where.empty()) where = name + " at t=" + std::to_string(t);
                    }
                }
            }
        }
        CHECK(!escaped, "motion produced a shape a body cannot hold: " + where);
    }

    // --- 5. A walk keeps its feet on the floor. ---
    //
    // The knee folds only on the swing leg. A knee that bends on the stance leg drops the figure
    // through the floor, and bodyPath's planting would then lift the whole body to compensate, which
    // reads as a bounce rather than a walk.
    {
        const Pose* walk = maz::film::poseNamed("walk");
        double lowest = 1e9;
        double highest = -1e9;
        for (int step = 0; step < 120; ++step) {
            const double phase = static_cast<double>(step) / 120.0;
            const double foot = maz::film::lowestFootY(200.0, maz::film::walkAt(*walk, phase));
            lowest = std::fmin(lowest, foot);
            highest = std::fmax(highest, foot);
        }
        char message[200];
        std::snprintf(message, sizeof(message),
                      "the walk bobs by %.1f units of a 200-unit figure", highest - lowest);
        CHECK(highest - lowest < 14.0, message);
    }

    // --- 6. Syllables, which are the clock the gesture, the mouth and the score all share. ---
    //
    // The first draft of this counted vowel groups -- a more defensible way to count syllables, and
    // the wrong one, because the browser counts words and multiplies by 1.7. A better answer that
    // disagrees puts the native renderer's gestures on a different clock from the browser's.
    {
        for (const auto& c : doc["syllables"].items()) {
            const int got = maz::film::syllablesFor(c["line"].asString());
            const int want = static_cast<int>(c["count"].asNumber());
            CHECK(got == want, "syllables for \"" + c["line"].asString() + "\": engine " +
                               std::to_string(got) + ", browser " + std::to_string(want));
        }
    }

    if (g_fail == 0) {
        std::printf("film motion: all checks passed (%zu cases, %zu pose choices, matched to 1e-12)\n",
                    doc["cases"].items().size(), doc["chosen"].items().size());
    }
    return g_fail == 0 ? 0 : 1;
}
