// tests/film/noise.cpp — verifies the ported noise generator (film Noise.hpp).
//
// Every set scatters something -- stars, bottles, rust, glints on water -- and none of it may be
// actually random: a film is identified by its seed, and "one idea and one seed give one film" is the
// promise the arcade rests on. So the scatter is a hash of the set name and the seed, and it has to
// produce the SAME numbers as the browser bit for bit, or a natively drawn room is the same room with
// the furniture moved.
//
// The ground truth is 8 keys x 80 triples generated by the browser, including the awkward ones: an
// empty key, a single character, and a seed at the top of the 32-bit range where the multiply wraps.
#include "maz/film/Noise.hpp"
#include "maz/io/Json.hpp"

#include <cmath>
#include <cstdio>
#include <string>

static int g_fail = 0;
#define CHECK(c, m) do{ if(!(c)){ std::printf("FAIL: %s\n",(m)); ++g_fail; } }while(0)

int main(int argc, char** argv) {
    const std::string path = argc > 1 ? argv[1] : "tests/film/noise-fixture.json";
    std::string text;
    if (!maz::io::readTextFile(path, text)) {
        std::printf("FAIL: could not read the noise fixture at %s\n", path.c_str());
        return 1;
    }
    const maz::io::JsonParseResult doc = maz::io::parseJson(text);
    CHECK(doc.ok, "the noise fixture is valid JSON");

    const maz::io::JsonValue& cases = doc.value["cases"];
    CHECK(cases.isArray() && cases.size() == 8u, "the fixture carries all 8 keys");

    int badHash = 0, badValue = 0;
    double worst = 0.0;
    std::string firstBad;
    for (const maz::io::JsonValue& c : cases.items()) {
        const std::string key = c["key"].asString();
        const std::uint32_t expected = static_cast<std::uint32_t>(c["hash"].asNumber(0.0));
        if (maz::film::hashText(key) != expected) {
            ++badHash;
            if (firstBad.empty()) {
                firstBad = "hash of \"" + key + "\" is " + std::to_string(maz::film::hashText(key)) +
                           ", expected " + std::to_string(expected);
            }
        }
        const auto mine = maz::film::noise(key, 80);
        const maz::io::JsonValue& theirs = c["values"];
        if (mine.size() != theirs.size()) {
            ++badValue;
            continue;
        }
        for (std::size_t i = 0; i < mine.size(); ++i) {
            for (std::size_t j = 0; j < 3; ++j) {
                const double them = theirs[i][j].asNumber(-1.0);
                const double d = std::fabs(mine[i][j] - them);
                worst = std::fmax(worst, d);
                if (d > 1e-15) {
                    ++badValue;
                    if (firstBad.empty()) {
                        firstBad = "\"" + key + "\" triple " + std::to_string(i) + " component " +
                                   std::to_string(j) + " off by " + std::to_string(d);
                    }
                }
            }
        }
    }
    if (badHash != 0) {
        std::printf("FAIL: %d hashes differ from the browser; first: %s\n", badHash, firstBad.c_str());
        ++g_fail;
    }
    if (badValue != 0) {
        std::printf("FAIL: %d noise values differ from the browser; first: %s\n", badValue,
                    firstBad.c_str());
        ++g_fail;
    }

    // --- Properties, asserted directly. ---
    {
        // Every value is a usable fraction: the sets multiply these by widths and heights.
        bool inRange = true;
        for (int seed = 0; seed < 200; ++seed) {
            const auto v = maz::film::noise("set-street-" + std::to_string(seed), 40);
            for (const auto& t : v) {
                for (const double x : t) {
                    if (!(x >= 0.0 && x < 1.0) || !std::isfinite(x)) {
                        inRange = false;
                    }
                }
            }
        }
        CHECK(inRange, "every noise value is a finite fraction in [0, 1)");
    }
    {
        // The same key twice gives the same scatter; a different one gives a different scatter.
        const auto a = maz::film::noise("set-bar-7", 20);
        const auto b = maz::film::noise("set-bar-7", 20);
        const auto c = maz::film::noise("set-bar-8", 20);
        CHECK(a == b, "the same key always gives the same scatter");
        CHECK(!(a == c), "one seed later is a different scatter");
    }
    {
        // Asking for more does not change what came before: a set that draws 22 items and one that
        // draws 80 must agree on the first 22, or the same room would refurnish itself.
        const auto few = maz::film::noise("set-woods-3", 22);
        const auto many = maz::film::noise("set-woods-3", 80);
        bool prefix = few.size() == 22u && many.size() == 80u;
        for (std::size_t i = 0; prefix && i < few.size(); ++i) {
            prefix = few[i] == many[i];
        }
        CHECK(prefix, "a longer scatter starts with the shorter one");
    }
    {
        CHECK(maz::film::noise("x", 0).empty(), "asking for nothing gives nothing");
        CHECK(maz::film::noise("x", -5).empty(), "asking for less than nothing gives nothing");
        CHECK(maz::film::noiseKey("bar", 42u) == "set-bar-42", "the key is built the browser's way");
    }

    if (g_fail == 0) {
        std::printf("film noise: all checks passed (8 keys x 80 triples, worst diff %.1g)\n", worst);
    }
    return g_fail == 0 ? 0 : 1;
}
