// tests/film/palette.cpp — verifies the ported film palette (film Palette.hpp).
//
// The palette is where a film's look comes from: a genre picks four base colours, the hour of the day
// multiplies them, and the scene's tension pulls the shadows. It is forty lines of arithmetic, and it
// has to give the SAME numbers in C++ as it does in the browser -- a native render with a palette
// half a shade off is a different film, and the difference would be invisible until someone put the
// two side by side.
//
// So there is no judgement in this test at all. Every one of 241 cases (10 genres x 4 hours x 6 moods,
// plus the unknown-genre and unknown-hour fallbacks) was generated by the browser and checked in;
// this reads them back and demands exact equality, channel for channel.
#include "maz/film/Palette.hpp"
#include "maz/io/Json.hpp"

#include <cstdio>
#include <string>

using maz::film::Palette;

static int g_fail = 0;
#define CHECK(c, m) do{ if(!(c)){ std::printf("FAIL: %s\n",(m)); ++g_fail; } }while(0)

static bool sameRgb(const maz::film::Rgb& a, const maz::io::JsonValue& b) {
    return b.isArray() && b.size() == 3 && a.r == b[static_cast<std::size_t>(0)].asInt(-1) &&
           a.g == b[static_cast<std::size_t>(1)].asInt(-1) &&
           a.b == b[static_cast<std::size_t>(2)].asInt(-1);
}

int main(int argc, char** argv) {
    const std::string fixture = argc > 1 ? argv[1] : "tests/film/palette-fixture.json";
    std::string text;
    if (!maz::io::readTextFile(fixture, text)) {
        std::printf("FAIL: could not read the palette fixture at %s\n", fixture.c_str());
        return 1;
    }
    const maz::io::JsonParseResult parsed = maz::io::parseJson(text);
    if (!parsed.ok) {
        std::printf("FAIL: the palette fixture is not valid JSON: %s\n", parsed.error.c_str());
        return 1;
    }

    const maz::io::JsonValue& cases = parsed.value["cases"];
    CHECK(cases.isArray() && cases.size() == 241u, "the fixture carries all 241 palette cases");

    int mismatches = 0;
    std::string firstBad;
    for (const maz::io::JsonValue& c : cases.items()) {
        const std::string genre = c["genre"].asString();
        const std::string time = c["time"].asString();
        const double mood = c["mood"].asNumber(0.0);  // double, for the reason Palette.hpp gives
        const Palette p = maz::film::paletteFor(genre, time, mood);

        const bool ok = sameRgb(p.key, c["key"]) && sameRgb(p.accent, c["accent"]) &&
                        sameRgb(p.sky, c["sky"]) && sameRgb(p.deep, c["deep"]) &&
                        sameRgb(p.ink, c["ink"]) && sameRgb(p.shadow, c["shadow"]);
        if (!ok) {
            ++mismatches;
            if (firstBad.empty()) {
                firstBad = genre + "/" + time + "/" + std::to_string(mood) + " key=(" +
                           std::to_string(p.key.r) + "," + std::to_string(p.key.g) + "," +
                           std::to_string(p.key.b) + ") sky=(" + std::to_string(p.sky.r) + "," +
                           std::to_string(p.sky.g) + "," + std::to_string(p.sky.b) + ")";
            }
        }
    }
    if (mismatches != 0) {
        std::printf("FAIL: %d of %zu palettes differ from the browser; first: %s\n", mismatches,
                    cases.size(), firstBad.c_str());
        ++g_fail;
    }

    // --- The two properties the whole look rests on, asserted directly. ---
    {
        // Day is brighter than night, and night keeps its shadows dark.
        const Palette day = maz::film::paletteFor("drama", "DAY", 0.4);
        const Palette night = maz::film::paletteFor("drama", "NIGHT", 0.4);
        CHECK(day.sky.r + day.sky.g + day.sky.b > night.sky.r + night.sky.g + night.sky.b,
              "a day sky is brighter than a night one");
        CHECK(day.lift > night.lift, "daylight reaches further into the shadows than night does");
    }
    {
        // An unknown genre or hour falls back rather than producing black.
        const Palette unknown = maz::film::paletteFor("nonsense", "NOPE", 0.4);
        const Palette drama = maz::film::paletteFor("drama", "NIGHT", 0.4);
        CHECK(unknown.key.r == drama.key.r && unknown.key.g == drama.key.g,
              "an unknown genre and hour fall back to drama at night, as the browser does");
    }
    {
        // Tension is clamped, not trusted.
        const Palette low = maz::film::paletteFor("thriller", "DUSK", -5.0);
        const Palette high = maz::film::paletteFor("thriller", "DUSK", 5.0);
        CHECK(low.tension == 0.0, "a mood below zero clamps to zero");
        CHECK(high.tension == 1.0, "a mood above one clamps to one");
    }
    {
        // Every channel stays a byte, for every case the films can produce.
        bool inRange = true;
        const char* genres[] = {"drama", "thriller", "horror", "comedy",  "romance",
                                "scifi", "mystery",  "fantasy", "heist",  "western"};
        const char* hours[] = {"NIGHT", "DAWN", "DAY", "DUSK"};
        for (const char* g : genres) {
            for (const char* h : hours) {
                for (int m = 0; m <= 100; ++m) {
                    const Palette p = maz::film::paletteFor(g, h, static_cast<double>(m) / 100.0);
                    const maz::film::Rgb all[] = {p.key, p.accent, p.sky, p.deep, p.ink, p.shadow};
                    for (const maz::film::Rgb& c : all) {
                        if (c.r < 0 || c.r > 255 || c.g < 0 || c.g > 255 || c.b < 0 || c.b > 255) {
                            inRange = false;
                        }
                    }
                }
            }
        }
        CHECK(inRange, "every channel of every palette stays inside 0..255");
    }

    if (g_fail == 0) {
        std::printf("film palette: all checks passed (%zu cases matched the browser exactly)\n",
                    cases.size());
    }
    return g_fail == 0 ? 0 : 1;
}
