#pragma once

// Umbrella header — pull in the whole Maz Engine public API.

#include "maz/anim/Tween.hpp"
#include "maz/audio/Audio.hpp"
#include "maz/core/Assert.hpp"
#include "maz/core/Config.hpp"
#include "maz/core/KeyValueStore.hpp"
#include "maz/core/Log.hpp"
#include "maz/core/Time.hpp"
#include "maz/ecs/World.hpp"
#include "maz/fx/Particles.hpp"
#include "maz/game/Collision.hpp"
#include "maz/game/FlyCamera.hpp"
#include "maz/game/NavGrid.hpp"
#include "maz/game/Shake.hpp"
#include "maz/game/SpatialGrid.hpp"
#include "maz/game/Steering.hpp"
#include "maz/game/Tilemap.hpp"
#include "maz/io/Serialize.hpp"
#include "maz/math/Math.hpp"
#include "maz/platform/Input.hpp"
#include "maz/platform/Paths.hpp"
#include "maz/platform/Window.hpp"
#include "maz/render/Model.hpp"
#include "maz/render/Renderer.hpp"
#include "maz/render/Shapes.hpp"
#include "maz/ui/DebugOverlay.hpp"
#include "maz/ui/Font.hpp"
#include "maz/ui/UI.hpp"
