/*
 * MadLibs Story Forge — built-in sample production
 * ------------------------------------------------
 * "The Museum Ghost" — a complete example project so the app opens already
 * populated: a story idea, its 30-minute script (Take A, in the app's Fountain-
 * like format), and a storyboard (pipe-delimited panels). Seeded once on first
 * run; the user can delete it. Exposed as window.MADLIBS_SAMPLE.
 */
(function (root) {
  'use strict';

  var SCRIPT = [
    'COLD OPEN',
    '',
    'INT. MERIDIAN MUSEUM - GRAND HALL - NIGHT',
    '',
    'Moonlight pours through a glass dome onto rows of glass cases. At the center, alone on a marble plinth under a single pin-light: THE NIGHTINGALE - a jeweled clockwork bird, no bigger than a fist.',
    '',
    'A figure in a docent\'s blazer strolls the hall, unhurried, sipping from a paper cup. This is JUNO VALE, 30s, disarming, the kind of calm that takes practice.',
    '',
    'JUNO (V.O.)',
    'There are two hundred cameras in this building. Forty guards. A vault door rated to survive a small war.',
    '',
    'Juno stops at the plinth. Looks at the Nightingale like an old friend.',
    '',
    'JUNO (V.O.)',
    'And exactly one thing nobody thought to secure.',
    '',
    'Juno taps the little brass placard beside the case: STAFF ACCESS.',
    '',
    'JUNO (V.O.)',
    'A uniform.',
    '',
    'A GUARD rounds the corner. Juno lifts the cup in a friendly toast and keeps walking. The guard nods, bored.',
    '',
    'SMASH TO TITLE',
    '',
    'END OF COLD OPEN',
    '',
    'ACT ONE',
    '',
    'INT. MERIDIAN MUSEUM - SECURITY OFFICE - DAY',
    '',
    'A wall of monitors. INES MARCH, 40s, sharp, sleeves rolled, watches the feeds like a chess player watches a board. Her boss, DIRECTOR PELL, hovers.',
    '',
    'PELL',
    'The board wants the Nightingale exhibit to be flawless. You were expensive, Ines. Be flawless.',
    '',
    'INES',
    '(not looking away from the screens)',
    'Nothing\'s flawless. It\'s just un-stolen so far.',
    '',
    'She freezes a frame: the docent from the cold open, mid-stroll.',
    '',
    'INES',
    'Who\'s that?',
    '',
    'PELL',
    'Staff. New hires for the gala.',
    '',
    'INES',
    '(quiet)',
    'We don\'t have new hires. We have a hiring freeze.',
    '',
    'INT. JUNO\'S APARTMENT - DAY',
    '',
    'Blueprints - not of the museum, but of the people. Photos of guards connected by string. Juno pins up one last photo: INES.',
    '',
    'JUNO',
    'There you are.',
    '',
    'A KNOCK. Juno\'s fence, BASIL, edgy, lets himself in.',
    '',
    'BASIL',
    'The buyer wants it by the gala. Three nights. You said this one was impossible.',
    '',
    'JUNO',
    'I said it was guarded. Impossible is the part I like.',
    '',
    'BASIL',
    'There\'s a new security chief. Ex-major-crimes. She\'s supposed to be -',
    '',
    'JUNO',
    '(smiling)',
    'Good. I know. That\'s why it\'s worth doing.',
    '',
    'INT. MERIDIAN MUSEUM - GRAND HALL - DAY',
    '',
    'Juno, in the blazer, gives a tour to a knot of donors - charming, word-perfect. Across the hall, Ines watches, arms folded. Their eyes meet. Juno gives a tiny, professional nod. Ines does not nod back.',
    '',
    'INES (V.O.)',
    'Rule one. The confident ones are not nervous because they belong. They are confident because they have done the reading.',
    '',
    'ACT TWO',
    '',
    'INT. MERIDIAN MUSEUM - VARIOUS - NIGHT',
    '',
    'The con versus the counter-con, cross-cut:',
    '',
    'Juno slips a magnet along a door seam. On Ines\'s monitor, a lock icon blinks amber. Ines circles it in grease pencil.',
    '',
    'Juno charms a guard, DUNNE, into propping a service door "just for a smoke." Ines, later, quietly reassigns Dunne to the parking level.',
    '',
    'Juno maps the camera blind spots with chalk dust. Next morning, a cleaner mops exactly those spots. Juno watches, realizing: she is letting me show her my plan.',
    '',
    'INT. MERIDIAN MUSEUM - CONSERVATION LAB - NIGHT',
    '',
    'Juno, alone, finally reaches the Nightingale\'s maintenance case. Gloves on. Reaches in -',
    '',
    'INES (O.S.)',
    'It\'s a fake.',
    '',
    'Juno does not turn. Ines steps from the dark, unhurried.',
    '',
    'INES',
    'The one on the floor is a fake too. The real one has been in my desk drawer since the day I started. I don\'t guard objects, Vale. I move them.',
    '',
    'JUNO',
    '(a real grin)',
    'You know my name.',
    '',
    'INES',
    'I know your work. Zurich. The one everyone thinks was two people. That was you.',
    '',
    'JUNO',
    'That\'s flattering and unprovable.',
    '',
    'INES',
    'I\'m not a cop anymore. I don\'t need proof. I need you to walk out and never come back.',
    '',
    'JUNO',
    'And if I don\'t?',
    '',
    'Ines holds up a small remote. Every door in the wing THUNKS locked at once.',
    '',
    'INES',
    'Then you\'re the most talented person I\'ve ever caught.',
    '',
    'ACT THREE',
    '',
    'INT. MERIDIAN MUSEUM - WEST WING - CONTINUOUS',
    '',
    'Trapped together. Juno paces; Ines waits. And Juno reads her - the tell she has been hiding.',
    '',
    'JUNO',
    'You didn\'t call this in. No alarm. No backup. You want to catch me personally. Because if the Nightingale is real and it goes missing on your watch, you\'re finished. But if it was never here - if the theft is of a fake -',
    '(realizing)',
    'You\'re stealing it. From the board. And you needed a ghost to blame.',
    '',
    'Silence. She does not deny it.',
    '',
    'INES',
    'I have a buyer. I don\'t have a thief good enough to make it look real.',
    '',
    'JUNO',
    'You have one now.',
    '(beat)',
    'Sixty-forty.',
    '',
    'INES',
    'Fifty. And you do exactly as I say.',
    '',
    'JUNO',
    '(offering a hand)',
    'Partners, then. For one night.',
    '',
    'They shake. Behind them, the fake Nightingale sings a tinny, mechanical song.',
    '',
    'TAG',
    '',
    'EXT. CITY ROOFTOP - DAWN',
    '',
    'Juno and Ines on a ledge, city gold behind them. A small velvet box between them. Juno opens it: the REAL Nightingale.',
    '',
    'INES',
    'You switched it. In the wing. When we shook hands.',
    '',
    'JUNO',
    '(innocent)',
    'Did I?',
    '',
    'INES',
    '(almost smiling)',
    'This isn\'t over.',
    '',
    'JUNO',
    'God, I hope not.',
    '',
    'Juno stands, pockets the bird, walks off into the light. Ines watches them go - and, despite herself, laughs.',
    '',
    'INES (V.O.)',
    'Rule two. Never work with someone better than you.',
    '(beat)',
    'Rule three. Break rule two.',
    '',
    'END OF EPISODE'
  ].join('\n');

  var STORYBOARD = [
    '# shot | framing | camera | slug | action | dialogue | seconds',
    '1 | WIDE | STATIC | INT. GRAND HALL - NIGHT | Moonlight through the glass dome; the Nightingale glows alone on its plinth. | | 6',
    '2 | MEDIUM | SLOW DOLLY | INT. GRAND HALL - NIGHT | Juno strolls the hall in a docent blazer, sipping coffee. | JUNO (V.O.): Two hundred cameras. Forty guards. | 7',
    '3 | INSERT | STATIC | INT. GRAND HALL - NIGHT | Juno\'s finger taps the brass placard: STAFF ACCESS. | JUNO (V.O.): A uniform. | 4',
    '4 | TITLE | STATIC | - | SMASH TO TITLE: THE MUSEUM GHOST. | | 2',
    '5 | WIDE | STATIC | INT. SECURITY OFFICE - DAY | Ines studies a wall of monitors; Pell hovers behind her. | PELL: Be flawless. | 6',
    '6 | CLOSE-UP | PUSH IN | INT. SECURITY OFFICE - DAY | Ines freezes a frame on the "docent" and narrows her eyes. | INES: We have a hiring freeze. | 5',
    '7 | MEDIUM | STATIC | INT. JUNO\'S APARTMENT - DAY | Juno pins Ines\'s photo to a web of string and faces. | JUNO: There you are. | 5',
    '8 | WIDE | HANDHELD | INT. GRAND HALL - DAY | Tour crowd; across the hall Juno and Ines lock eyes. Juno nods; Ines does not. | INES (V.O.): They\'ve done the reading. | 6',
    '9 | MONTAGE | MIXED | INT. MUSEUM - VARIOUS - NIGHT | Con vs counter-con: magnet on a seam, a propped door, chalk-dust blind spots - each move quietly undone. | | 12',
    '10 | MEDIUM | STATIC | INT. CONSERVATION LAB - NIGHT | Juno reaches into the Nightingale\'s case as Ines speaks from the dark. | INES (O.S.): It\'s a fake. | 6',
    '11 | OTS | STATIC | INT. CONSERVATION LAB - NIGHT | Over Juno\'s shoulder to Ines, holding a remote. Doors THUNK locked. | INES: The most talented person I\'ve ever caught. | 7',
    '12 | TWO-SHOT | SLOW PUSH | INT. WEST WING - NIGHT | Juno reads Ines\'s tell and lays out the real scheme; a deal is struck. | JUNO: Partners, then. For one night. | 9',
    '13 | WIDE | CRANE | EXT. CITY ROOFTOP - DAWN | Juno and Ines on a ledge, gold city behind; the velvet box between them. | INES: You switched it. | 7',
    '14 | CLOSE-UP | STATIC | EXT. CITY ROOFTOP - DAWN | The real Nightingale in Juno\'s palm; Juno pockets it and walks into the light. | JUNO: God, I hope not. | 6'
  ].join('\n');

  var SAMPLE = {
    signature: 'sample|museum-ghost',
    slug: 'museum-ghost-sample',
    title: 'The Museum Ghost',
    genre: 'heist',
    seed: 0,
    example: true,
    status: 'storyboarded',
    scriptUrl: '',
    storyboardUrl: '',
    story: {
      id: 'museum-ghost',
      title: 'The Museum Ghost',
      genre: 'heist',
      seed: 0,
      signature: 'sample|museum-ghost',
      beats: [
        { label: 'Logline', text: 'A master thief poses as museum staff to lift the legendary automaton known as the Nightingale from the most guarded museum in the city.' },
        { label: 'Setup', text: 'Juno Vale has never been caught, slipping through the Meridian Museum like one of its own shadows.' },
        { label: 'Inciting Incident', text: 'A mysterious client offers a fortune for the Nightingale, displayed under forty layers of security before the gala.' },
        { label: 'Conflict', text: 'The museum\'s new head of security, Ines March, is relentlessly brilliant and seems to anticipate Juno\'s every move.' },
        { label: 'Climax', text: 'Cornered in the west wing, Juno realizes Ines wants to steal the Nightingale herself and needs a ghost to blame.' },
        { label: 'Resolution', text: 'The two strike an uneasy partnership; the Nightingale vanishes, and Juno disappears into the dawn, one step ahead.' }
      ]
    },
    script: { text: SCRIPT, updatedAt: null },
    storyboard: { text: STORYBOARD, updatedAt: null }
  };

  root.MADLIBS_SAMPLE = SAMPLE;
  if (typeof module !== 'undefined' && module.exports) module.exports = SAMPLE;
})(typeof window !== 'undefined' ? window : this);
