"""VERIFY — the tests are the judge, and there is no arguing with them.

Green: push the branch and open a DRAFT pull request. Never a merge, never a
push to main. Red: the caller abandons the branch and the failure goes into the
ledger, where tomorrow night's SENSE will read it.

The pull request body is written for a human skimming it over coffee: what was
picked, where the idea came from, the arithmetic that chose it, and every file
touched.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from .checks import commands_for
from .do import CrewOutcome
from .github import api, repo_slug

BASE_BRANCH = "main"
CHECK_TIMEOUT_S = 900


@dataclass(frozen=True)
class CheckResult:
    ok: bool
    ran: tuple[str, ...]
    output: str


def _default_runner(cmd: tuple[str, ...], root: Path | None) -> tuple[int, str]:
    proc = subprocess.run(list(cmd), cwd=str(root or Path.cwd()),
                          capture_output=True, text=True, timeout=CHECK_TIMEOUT_S)
    return (proc.returncode, (proc.stdout or "") + (proc.stderr or ""))


def run_checks(zone: str, root: Path | None, runner=None) -> CheckResult:
    """Run every command for the zone, stopping at the first failure."""
    run = runner or _default_runner
    ran: list[str] = []
    for cmd in commands_for(zone):
        ran.append(" ".join(cmd))
        try:
            code, output = run(cmd, root)
        except Exception as exc:  # noqa: BLE001
            return CheckResult(False, tuple(ran), f"{ran[-1]} could not run: {exc}")
        if code != 0:
            return CheckResult(False, tuple(ran), output[-2000:])
    return CheckResult(True, tuple(ran), "")


def _pr_body(outcome: CrewOutcome, chosen: dict) -> str:
    c = chosen["candidate"]
    files = "\n".join(f"- `{p}`" for p in outcome.files) or "- (none recorded)"
    cost = f"${outcome.cost_usd:.2f}" if outcome.cost_usd is not None else "not measured"
    return (
        f"Opened by **the Forge** on its nightly run. This is a draft — nothing merges "
        f"without you.\n\n"
        f"**What it picked:** {c['task']}\n\n"
        f"**Where the idea came from:** `{c['source']}`\n\n"
        f"**Why it won tonight:** score **{chosen['score']}** "
        f"= value {chosen['value']} x confidence {chosen['confidence']} "
        f"/ (1 + risk {chosen['risk']}), in zone `{chosen['zone']}`.\n\n"
        f"**Files touched:**\n{files}\n\n"
        f"**Cost:** {cost} over {outcome.duration_min:.1f} minutes.\n\n"
        f"---\n_Generated by [Claude Code](https://claude.ai/code)_\n"
    )


def open_draft_pr(outcome: CrewOutcome, chosen: dict, root: Path | None,
                  slug: str | None = None, poster=None) -> int | None:
    """Open a draft PR for the branch. Returns the PR number, or None."""
    slug = slug if slug is not None else repo_slug(root)
    if not slug:
        return None
    post = poster or (lambda path, body: api(path, method="POST", body=body))
    task = chosen["candidate"]["task"]
    payload = {
        "title": f"forge: {task[:70]}",
        "head": outcome.branch,
        "base": BASE_BRANCH,
        "draft": True,
        "body": _pr_body(outcome, chosen),
    }
    result = post(f"/repos/{slug}/pulls", payload)
    number = result.get("number") if isinstance(result, dict) else None
    return int(number) if number else None
