/*
 * Render the model as docs/INVENTORY.md.
 *
 * Two rules shape this file. First, the output is *deterministic* — no
 * timestamp, no run id, nothing that changes when the repo does not — because
 * `inventory --check` compares a fresh render against the committed one and
 * fails CI on a difference. A clock in the output would make that gate cry
 * wolf every night. Second, it is written for a reader who does not code: each
 * section says what it is looking at and why the gap matters before it shows
 * the table.
 */

const BAR_WIDTH = 10;

function bar(fraction) {
  const filled = Math.round(fraction * BAR_WIDTH);
  return '█'.repeat(filled) + '░'.repeat(BAR_WIDTH - filled);
}

function esc(s) {
  return String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ').trim();
}

function clip(s, n) {
  const t = esc(s);
  return t.length <= n ? t : t.slice(0, n - 1).replace(/[ ,;:.—-]+$/, '') + '…';
}

function gaps(artifact) {
  const failed = artifact.checks.filter((c) => !c.ok).map((c) => c.missing || c.label);
  return failed.length ? failed.join('; ') : '—';
}

export function render(model) {
  const s = model.stats;
  const L = [];
  const p = (...lines) => L.push(...lines);

  p('# The Maz Inventory — everything built here, and what each one still needs');
  p('');
  p('> Generated by `node tools/inventory/main.mjs --write`. Do not edit by hand: the next run');
  p('> overwrites it, and `--check` fails CI when this file and the repository disagree.');
  p('');
  p('This is one document answering three questions. **What exists** — every program, demo, tool,');
  p('gate and document in this repository, counted and described. **What is missing from each** —');
  p('measured against a short list of things a finished piece of work has, not against taste. And');
  p('**what each one could lend the others** — because most of the value left in a repository this');
  p('size is in the wiring between the parts, not in any one part.');
  p('');

  // ---------------------------------------------------------------- numbers
  p('## The numbers');
  p('');
  p('| | Count | |');
  p('|---|---:|---|');
  p(`| Native games and demos (\`apps/\`) | ${s.apps} | ${fmt(s.linesOfApps)} lines |`);
  p(`| Engine capabilities (\`engine/include/maz/\`) | ${s.engineModules} | ${fmt(s.linesOfEngine)} lines across ${s.engineSubsystems} subsystems |`);
  p(`| C++ test files (\`tests/\`) | ${s.cppTests} | |`);
  p(`| Browser apps and games | ${s.webApps} | ${fmt(s.linesOfWeb)} lines |`);
  p(`| Python tools | ${s.pyTools} | |`);
  p(`| CI gates (\`scripts/\`) | ${s.gates} | |`);
  p(`| Build and codegen helpers (\`tools/\`) | ${s.buildTools} | |`);
  p(`| Documents (\`docs/\`) | ${s.docs} | |`);
  p(`| **Catalogued artifacts** | **${s.totalArtifacts}** | |`);
  p('');
  p('| Health signal | Score | |');
  p('|---|---:|---|');
  p(`| Completeness checks passing | ${pct(s.checksPassed, s.checksTotal)}% | ${bar(s.checksPassed / Math.max(1, s.checksTotal))} ${s.checksPassed} of ${s.checksTotal} |`);
  p(`| Apps that run headless in CI | ${s.appsHeadless}% | ${bar(s.appsHeadless / 100)} |`);
  p(`| Apps with a golden screenshot | ${s.appsGolden}% | ${bar(s.appsGolden / 100)} |`);
  p(`| Engine modules a test exercises | ${s.modulesTested}% | ${bar(s.modulesTested / 100)} |`);
  p(`| Engine modules an app demonstrates | ${s.modulesDemoed}% | ${bar(s.modulesDemoed / 100)} |`);
  p(`| Open tasks in the queue below | ${s.openTasks} | |`);
  p('');

  // ------------------------------------------------------------- catalogue
  p('## 1. Everything you have built');
  p('');

  p('### Browser apps and games');
  p('');
  p('Playable and usable in a browser with nothing installed. These are the projects most people');
  p('will ever see, and the ones that can most easily lend each other capabilities.');
  p('');
  p('| Project | What it is | Lines | Publishes | Consumes | Gaps |');
  p('|---|---|---:|---|---|---|');
  for (const w of model.webApps) {
    p(`| **${esc(w.name)}** <br>\`${w.path}/\` | ${clip(w.blurb, 160)} | ${fmt(w.loc)} | ${w.publishes.join(', ') || '—'} | ${w.consumes.join(', ') || '—'} | ${gaps(w)} |`);
  }
  p('');

  p('### Python tools');
  p('');
  p('| Tool | What it does | Lines | Commands | Tests | CI | Gaps |');
  p('|---|---|---:|---|---:|---|---|');
  for (const t of model.pyTools) {
    p(`| **${esc(t.name)}** | ${clip(t.blurb, 120) || '—'} | ${fmt(t.loc)} | ${t.entryPoints.join(', ') || '—'} | ${t.tests.length} | ${t.ciWorkflows.join(', ') || '—'} | ${gaps(t)} |`);
  }
  p('');

  p('### The engine, by capability');
  p('');
  p('Every header under `engine/include/maz/` is one capability. The columns say how many of a');
  p('subsystem\'s modules a test exercises and how many an app under `apps/` puts on screen — a');
  p('module with neither is working code nobody can find.');
  p('');
  p('| Subsystem | Modules | Tested | Demonstrated |');
  p('|---|---:|---:|---:|');
  for (const [sub, mods] of bySubsystem(model.modules)) {
    const tested = mods.filter((m) => m.testedBy.length).length;
    const demoed = mods.filter((m) => m.demoedBy.length).length;
    p(`| \`${sub}\` | ${mods.length} | ${tested} (${pct(tested, mods.length)}%) | ${demoed} (${pct(demoed, mods.length)}%) |`);
  }
  p('');
  p('<details><summary>Every engine module by name</summary>');
  p('');
  for (const [sub, mods] of bySubsystem(model.modules)) {
    p(`**\`${sub}\`** — ${mods.map((m) => marker(m) + m.name).join(', ')}`);
    p('');
  }
  p('Legend: no mark = tested and demonstrated · `~` = tested, no demo app · `!` = neither.');
  p('');
  p('</details>');
  p('');

  p('### Native games and demos');
  p('');
  p('Each is a real, buildable program under `apps/`, most of them a focused demonstration of one');
  p('engine capability, a handful of them complete games.');
  p('');
  p('| App | What it shows | Lines | Headless | Golden | Gaps |');
  p('|---|---|---:|:-:|:-:|---|');
  for (const a of model.apps) {
    p(`| **${esc(a.name)}** | ${clip(a.blurb || a.title, 150)} | ${fmt(a.loc)} | ${a.headless ? '✓' : '·'} | ${a.golden ? '✓' : '·'} | ${gaps(a)} |`);
  }
  p('');

  p('### CI gates, build helpers and documents');
  p('');
  p('| Artifact | What it does | Gaps |');
  p('|---|---|---|');
  for (const g of model.gates) p(`| \`${g.path}\` | ${clip(g.blurb, 130)} | ${gaps(g)} |`);
  for (const t of model.buildTools) p(`| \`${t.path}\` | ${clip(t.blurb, 130) || '—'} | ${gaps(t)} |`);
  for (const d of model.docs) p(`| \`${d.path}\` | ${clip(d.blurb, 130)} | ${gaps(d)} |`);
  p('');

  // ----------------------------------------------------------- completeness
  p('## 2. What "more complete" means here');
  p('');
  p('Completeness is measured against checks that can be answered by looking at the repository,');
  p('not by judging the work. Every failing check below is a specific, finishable job.');
  p('');
  p('| Kind | Check | Passing |');
  p('|---|---|---:|');
  for (const row of checkRollup(model)) {
    p(`| ${row.kind} | ${row.label} | ${row.passed}/${row.total} (${pct(row.passed, row.total)}%) |`);
  }
  p('');

  // ------------------------------------------------------------- synergies
  p('## 3. How each program can make the others better');
  p('');
  p('The repository already has a mechanism for this: `shared/exchange.json` records which project');
  p('lends a capability to which, and `scripts/check-exchange.mjs` fails CI if a page reaches across');
  p('projects without declaring it. Everything below is written to end up in that manifest.');
  p('');

  p('### Found by the scan');
  p('');
  for (const o of model.opportunities) {
    p(`#### ${o.title}`);
    p('');
    p(wrap(o.detail));
    p('');
    p(`<sub>${o.subjects.length} affected · effort: ${o.effort} · value: ${'★'.repeat(o.value)}` +
      `${o.covers ? ` · queued below as the \`${o.covers}\` task` : ''}</sub>`);
    p('');
  }

  p('### Already wired together');
  p('');
  p('What the programs here lend each other today. Nothing to do — this is the section that says');
  p('the wiring works, and the shape the proposals below are aiming for.');
  p('');
  for (const pr of model.realized) {
    p(`#### ${pr.title}`);
    p('');
    p(`\`${pr.from.join('`, `')}\` → \`${pr.to.join('`, `')}\``);
    p('');
    p(wrap(pr.detail));
    p('');
  }

  p('### Reviewed pairings');
  p('');
  p('These are judgement calls, kept in `tools/inventory/lib/synergy.mjs` so they can be read and');
  p('argued with. Each names real artifacts; one that names something deleted fails `--check`.');
  p('');
  for (const pr of model.pairings) {
    p(`#### ${pr.title}`);
    p('');
    p(`\`${pr.from.join('`, `')}\` → \`${pr.to.join('`, `')}\``);
    p('');
    p(wrap(pr.detail));
    p('');
    p(`<sub>effort: ${pr.effort} · value: ${'★'.repeat(pr.value)}</sub>`);
    p('');
  }
  if (model.stalePairings.length) {
    p('### ⚠ Stale pairings');
    p('');
    for (const st of model.stalePairings) {
      p(`- **${st.title}** names artifacts that no longer exist: \`${st.missing.join('`, `')}\``);
    }
    p('');
  }

  // ----------------------------------------------------------------- queue
  p('## 4. The work queue');
  p('');
  p('Every gap above, ranked. **P1** is something broken or unprotected, **P2** is a real coverage');
  p('gap, **P3** is polish. `forge/forge/signals/inventory.py` reads the same list out of');
  p('`docs/inventory.json`, so the nightly Forge can pick work straight off it.');
  p('');
  for (const level of [1, 2, 3]) {
    const rows = model.queue.filter((t) => t.priority === level);
    if (!rows.length) continue;
    p(`### P${level} — ${['', 'broken or unprotected', 'coverage gaps', 'polish'][level]} (${rows.length})`);
    p('');
    for (const t of rows) {
      p(`- **${esc(t.title)}**`);
      p(`  <br>${clip(t.detail, 600)}`);
    }
    p('');
  }

  p('---');
  p('');
  p('Regenerate with `node tools/inventory/main.mjs --write`; verify with `--check`.');
  p('');
  return L.join('\n');
}

function marker(m) {
  if (m.testedBy.length === 0 && m.demoedBy.length === 0) return '!';
  if (m.demoedBy.length === 0) return '~';
  return '';
}

function bySubsystem(modules) {
  const map = new Map();
  for (const m of modules) {
    if (!map.has(m.subsystem)) map.set(m.subsystem, []);
    map.get(m.subsystem).push(m);
  }
  return [...map.entries()].sort((a, b) => b[1].length - a[1].length);
}

function checkRollup(model) {
  const rows = new Map();
  for (const a of model.all) {
    for (const c of a.checks) {
      const key = `${a.kind}|${c.id}`;
      if (!rows.has(key)) rows.set(key, { kind: a.kind, label: c.label, passed: 0, total: 0 });
      const r = rows.get(key);
      r.total += 1;
      if (c.ok) r.passed += 1;
    }
  }
  return [...rows.values()].sort(
    (a, b) => a.passed / a.total - b.passed / b.total || (a.kind < b.kind ? -1 : 1)
  );
}

function pct(n, d) {
  return d ? Math.round((n / d) * 100) : 100;
}

function fmt(n) {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

/** Soft-wrap prose to ~96 columns so the Markdown source stays readable. */
function wrap(text, width = 96) {
  const words = String(text).split(/\s+/);
  const lines = [];
  let line = '';
  for (const w of words) {
    if (line && line.length + 1 + w.length > width) {
      lines.push(line);
      line = w;
    } else {
      line = line ? `${line} ${w}` : w;
    }
  }
  if (line) lines.push(line);
  return lines.join('\n');
}
