// film/tests/film-3d.test.js — the 3D renderer in the browser draws the same film as the one on the
// command line.
//
// There is now one renderer compiled two ways: a native binary and a WebAssembly module inside a web
// page. That is only worth having if they agree. A film that cuts at the same moments but paints a
// different picture is not one film rendered twice, it is two opinions about what the film is — and
// the whole reason the 3D path was written headless, with no window and no graphics driver, was so
// that this could be true.
//
// So the test renders the same moments of the same reel through the module and compares them against
// frames the native renderer wrote, pixel for pixel. It also checks the things a page needs before it
// can show anything: that a bad reel is refused with a reason rather than a crash, that the edit is
// the edit, and that a frame is actually a picture rather than a rectangle of one colour.
//
//   node film/tests/film-3d.test.js
//
// The fixture frames are generated by tools/make-3d-fixture.sh and committed next to this file.

'use strict';

var fs = require('fs');
var path = require('path');
var zlib = require('zlib');

var HERE = __dirname;
var ROOT = path.resolve(HERE, '..', '..');
var WASM_DIR = path.join(ROOT, 'film', 'wasm');
var FIXTURE_DIR = path.join(HERE, 'fixtures-3d');

var failures = [];
var checks = 0;

function check(ok, what) {
  checks++;
  if (!ok) failures.push(what);
}

function near(got, want, tol, what) {
  checks++;
  if (!(Math.abs(got - want) <= tol)) {
    failures.push(what + ' (got ' + got + ', wanted ' + want + ' +/- ' + tol + ')');
  }
}

// A binary PPM (P6) as written by the native renderer: width, height, then RGB triples.
function readPpm(file) {
  var buf = fs.readFileSync(file);
  if (/\.gz$/.test(file)) buf = zlib.gunzipSync(buf);
  // Header: "P6\n<w> <h>\n255\n"
  var header = buf.slice(0, 64).toString('latin1');
  var m = /^P6\s+(\d+)\s+(\d+)\s+(\d+)\s/.exec(header);
  if (!m) throw new Error('not a P6 file: ' + file);
  var offset = m[0].length;
  return { width: +m[1], height: +m[2], rgb: buf.slice(offset) };
}

function run(Module) {
  var load = Module.cwrap('maz3d_load', 'number', ['string']);
  var errorPtr = Module.cwrap('maz3d_error', 'number', []);
  var titlePtr = Module.cwrap('maz3d_title', 'number', []);
  var duration = Module.cwrap('maz3d_duration', 'number', []);
  var shots = Module.cwrap('maz3d_shots', 'number', []);
  var people = Module.cwrap('maz3d_people', 'number', []);
  var shotAt = Module.cwrap('maz3d_shot_at', 'number', ['number']);
  var render = Module.cwrap('maz3d_render', 'number',
                            ['number', 'number', 'number', 'number', 'number', 'number', 'number']);

  function errorText() { return Module.UTF8ToString(errorPtr()); }

  // ------------------------------------------------------------------ 1. a reel that is not a reel
  check(load('') === 0, 'an empty string is not a film reel');
  check(errorText().length > 0, 'and it says why rather than failing silently');
  check(load('{"nope":1}') === 0, 'neither is some other JSON object');
  check(errorText().length > 0, 'and that says why too');
  check(load('{ this is not json at all') === 0, 'nor is a broken document');

  // ------------------------------------------------------------------ 2. a real one
  var manifest = JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, 'manifest.json'), 'utf8'));
  var reelText = fs.readFileSync(path.join(FIXTURE_DIR, manifest.reel), 'utf8');
  check(load(reelText) === 1, 'a real reel loads');
  check(errorText() === '', 'with no error left over from the failures before it');
  check(Module.UTF8ToString(titlePtr()) === manifest.title, 'and it knows the title');
  near(duration(), manifest.duration, 0.001, 'and how long the film is');
  check(shots() === manifest.shots, 'and how many shots are in it');
  check(people() === manifest.people, 'and how many people are in it');

  // The edit is the edit: the shot on screen at a moment is the one the reel says.
  var wrongShot = 0;
  manifest.frames.forEach(function (f) {
    if (shotAt(f.time) !== f.shot) wrongShot++;
  });
  check(wrongShot === 0, 'the browser cuts the film at the same moments the reel does');

  // ------------------------------------------------------------------ 3. the same picture
  //
  // The browser has to draw the film the command line draws. How exactly, and why not more exactly
  // than this, is the whole of what follows — because the answer changed once the question was
  // measured properly.
  //
  // This test used to demand every pixel be identical, and that standard earned its keep. The first
  // version allowed a step or two, on the reasoning that two compilers round arithmetic differently.
  // It failed anyway: a tenth of the pixels in a street scene disagreed, by up to 42 steps. Blurring
  // did not absorb it, so it was not sub-pixel. Turning the shadows off did not change it, so it was
  // not the lighting. Cropping the worst pixel and looking at both showed the same buildings STANDING
  // IN DIFFERENT PLACES. The cause was two dice rolls inside one function call: C++ does not specify
  // which argument is evaluated first, GCC and Clang really do choose differently, so the random
  // numbers were dealt out in a different order and the skyline came out different — same film, same
  // seed, different compiler. One roll per statement fixed it.
  //
  // What was NOT true is the sentence that went in the docs afterwards: that the two builds agree on
  // every pixel. They agree on every pixel of the nine frames that were in the fixture. Sweeping
  // fifty-eight moments of the same reel found frames where they do not — and looking at one showed
  // what it is. Not blocks in the wrong place: a single diagonal edge, the lit side of a doorway,
  // with a scatter of pixels along it and nothing anywhere else in frame.
  //
  // That is sub-pixel geometry, and it is not fixable by rounding more carefully. The two builds
  // reach `sin`, `cos` and `tan` through different C libraries, which are allowed to differ in the
  // last bit and do. A vertex therefore projects perhaps a hundred-thousandth of a pixel apart in the
  // two builds, which is invisible everywhere except on a pixel whose centre sits within a
  // hundred-thousandth of a triangle edge — where coverage flips, and if that edge divides a lit wall
  // from a dark one the pixel jumps several steps. Quantising the geometry does not help: it makes
  // the disagreement rarer and correspondingly bigger, and the product does not move. Only arithmetic
  // that is bit-identical in both builds would close it, which means shipping our own trigonometry,
  // and that is a real piece of work rather than a rounding tweak.
  //
  // So the standard is now a measured one, and the fixture deliberately includes the worst moment
  // found (frame-09) rather than nine that happen to be clean. What the two phenomena score:
  //
  //                            worst step    pixels differing    mean difference
  //   edge coverage, measured       5             3.84%              0.043
  //   the dice bug, as it was      42            ~10%              ~2.0
  //
  // The gates sit between them, nearer the measurement: a few times what sub-pixel edges can do, and
  // several times under what a genuine divergence did. A logic bug moves geometry, and moved geometry
  // is loud in all three numbers at once.
  var WORST_STEP = 12;     // 2.4x the measured edge flip, 3.5x under the dice bug
  var MOST_PIXELS = 0.06;  // 1.6x the measured share, under the dice bug's tenth
  var MEAN_STEP = 0.25;    // 6x the measured mean, 8x under the dice bug

  var worst = 0;
  var worstFrame = '';
  var differing = 0;
  var samples = 0;
  var loudest = 0;         // the largest share of any one frame
  var loudestMean = 0;     // and the largest mean difference of any one frame
  var loudestFrame = '';

  manifest.frames.forEach(function (f) {
    var want = readPpm(path.join(FIXTURE_DIR, f.file));
    // Shutter 0, explicitly. Every fixture frame is a lone still and a still has no previous
    // camera to smear from, so the shutter could not fire here anyway — but saying so beats
    // relying on an absent argument becoming a zero.
    var ptr = render(f.time, want.width, want.height, manifest.supersample, manifest.shadows, 0,
                     manifest.corners == null ? 0 : manifest.corners);
    check(ptr !== 0, 'the module returns a frame for ' + f.file);
    if (!ptr) return;
    var got = Module.HEAPU8.subarray(ptr, ptr + want.width * want.height * 4);

    var count = want.width * want.height;
    var here = 0;
    var sum = 0;
    for (var i = 0, p = 0; i < count; i++, p += 3) {
      var d = 0;
      for (var c = 0; c < 3; c++) {
        var v = Math.abs(got[i * 4 + c] - want.rgb[p + c]);
        sum += v;
        if (v > d) d = v;
      }
      if (d > 0) { here++; differing++; }
      if (d > worst) { worst = d; worstFrame = f.file; }
    }
    var share = here / count;
    var mean = sum / (count * 3);
    if (share > loudest) { loudest = share; loudestFrame = f.file; }
    if (mean > loudestMean) { loudestMean = mean; }
    samples++;
  });

  check(samples === manifest.frames.length, 'every fixture frame was rendered');
  check(worst <= WORST_STEP,
        'no pixel of the browser\'s film is more than ' + WORST_STEP + ' steps from the command ' +
        'line\'s — worst was ' + worst + (worstFrame ? ' in ' + worstFrame : '') +
        ', over ' + differing + ' pixels in all');
  check(loudest <= MOST_PIXELS,
        'the disagreement stays on edges rather than spreading over the frame — ' +
        (loudest * 100).toFixed(2) + '% of one frame differed' +
        (loudestFrame ? ' (' + loudestFrame + ')' : '') + ', the gate is ' +
        (MOST_PIXELS * 100).toFixed(0) + '%');
  check(loudestMean <= MEAN_STEP,
        'averaged over the whole frame the two builds draw the same picture — worst mean ' +
        'difference ' + loudestMean.toFixed(4) + ' of 255, the gate is ' + MEAN_STEP);

  // ------------------------------------------------------------------ 4. it is a picture
  {
    var f = manifest.frames[manifest.frames.length - 1];
    var ptr = render(f.time, 320, 136, 1, 1, 0, 0);
    check(ptr !== 0, 'a frame comes back at a size nobody asked for in the fixture');
    var px = Module.HEAPU8.subarray(ptr, ptr + 320 * 136 * 4);
    var seen = {};
    var lit = 0;
    for (var i = 0; i < 320 * 136; i++) {
      seen[px[i * 4] + ',' + px[i * 4 + 1] + ',' + px[i * 4 + 2]] = 1;
      if (px[i * 4] + px[i * 4 + 1] + px[i * 4 + 2] > 24) lit++;
    }
    check(Object.keys(seen).length > 40, 'a frame has a picture in it, not one flat colour');
    check(lit > 320 * 136 * 0.1, 'and enough of it is lit to see');
  }

  // ------------------------------------------------------------------ 5. it refuses the impossible
  check(render(0, 2, 2, 1, 1, 0, 0) === 0, 'a frame smaller than a thumbnail is refused, not crashed on');
  check(load('nonsense') === 0, 'and a bad reel after a good one is still refused');
  check(render(0, 320, 136, 1, 1, 0, 0) === 0, 'after which there is no film to render');
}

var factory = require(path.join(WASM_DIR, 'film3d.js'));
factory().then(function (Module) {
  try {
    run(Module);
  } catch (err) {
    failures.push('threw: ' + (err && err.stack ? err.stack : err));
  }
  if (failures.length) {
    failures.forEach(function (f) { console.log('FAIL: ' + f); });
    console.log(failures.length + ' failed of ' + checks);
    process.exit(1);
  }
  console.log('film 3d: all ' + checks + ' checks passed');
}).catch(function (err) {
  console.log('FAIL: the module would not start: ' + (err && err.stack ? err.stack : err));
  process.exit(1);
});
