// film/tests/film-3d.test.js — the 3D renderer in the browser draws the same film as the one on the
// command line.
//
// There is now one renderer compiled two ways: a native binary and a WebAssembly module inside a web
// page. That is only worth having if they agree. A film that cuts at the same moments but paints a
// different picture is not one film rendered twice, it is two opinions about what the film is — and
// the whole reason the 3D path was written headless, with no window and no graphics driver, was so
// that this could be true.
//
// So the test renders the same moments of the same reel through the module and compares them against
// frames the native renderer wrote, pixel for pixel. It also checks the things a page needs before it
// can show anything: that a bad reel is refused with a reason rather than a crash, that the edit is
// the edit, and that a frame is actually a picture rather than a rectangle of one colour.
//
//   node film/tests/film-3d.test.js
//
// The fixture frames are generated by tools/make-3d-fixture.sh and committed next to this file.

'use strict';

var fs = require('fs');
var path = require('path');
var zlib = require('zlib');

var HERE = __dirname;
var ROOT = path.resolve(HERE, '..', '..');
var WASM_DIR = path.join(ROOT, 'film', 'wasm');
var FIXTURE_DIR = path.join(HERE, 'fixtures-3d');

var failures = [];
var checks = 0;

function check(ok, what) {
  checks++;
  if (!ok) failures.push(what);
}

function near(got, want, tol, what) {
  checks++;
  if (!(Math.abs(got - want) <= tol)) {
    failures.push(what + ' (got ' + got + ', wanted ' + want + ' +/- ' + tol + ')');
  }
}

// A binary PPM (P6) as written by the native renderer: width, height, then RGB triples.
function readPpm(file) {
  var buf = fs.readFileSync(file);
  if (/\.gz$/.test(file)) buf = zlib.gunzipSync(buf);
  // Header: "P6\n<w> <h>\n255\n"
  var header = buf.slice(0, 64).toString('latin1');
  var m = /^P6\s+(\d+)\s+(\d+)\s+(\d+)\s/.exec(header);
  if (!m) throw new Error('not a P6 file: ' + file);
  var offset = m[0].length;
  return { width: +m[1], height: +m[2], rgb: buf.slice(offset) };
}

function run(Module) {
  var load = Module.cwrap('maz3d_load', 'number', ['string']);
  var errorPtr = Module.cwrap('maz3d_error', 'number', []);
  var titlePtr = Module.cwrap('maz3d_title', 'number', []);
  var duration = Module.cwrap('maz3d_duration', 'number', []);
  var shots = Module.cwrap('maz3d_shots', 'number', []);
  var people = Module.cwrap('maz3d_people', 'number', []);
  var shotAt = Module.cwrap('maz3d_shot_at', 'number', ['number']);
  var render = Module.cwrap('maz3d_render', 'number',
                            ['number', 'number', 'number', 'number', 'number', 'number']);

  function errorText() { return Module.UTF8ToString(errorPtr()); }

  // ------------------------------------------------------------------ 1. a reel that is not a reel
  check(load('') === 0, 'an empty string is not a film reel');
  check(errorText().length > 0, 'and it says why rather than failing silently');
  check(load('{"nope":1}') === 0, 'neither is some other JSON object');
  check(errorText().length > 0, 'and that says why too');
  check(load('{ this is not json at all') === 0, 'nor is a broken document');

  // ------------------------------------------------------------------ 2. a real one
  var manifest = JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, 'manifest.json'), 'utf8'));
  var reelText = fs.readFileSync(path.join(FIXTURE_DIR, manifest.reel), 'utf8');
  check(load(reelText) === 1, 'a real reel loads');
  check(errorText() === '', 'with no error left over from the failures before it');
  check(Module.UTF8ToString(titlePtr()) === manifest.title, 'and it knows the title');
  near(duration(), manifest.duration, 0.001, 'and how long the film is');
  check(shots() === manifest.shots, 'and how many shots are in it');
  check(people() === manifest.people, 'and how many people are in it');

  // The edit is the edit: the shot on screen at a moment is the one the reel says.
  var wrongShot = 0;
  manifest.frames.forEach(function (f) {
    if (shotAt(f.time) !== f.shot) wrongShot++;
  });
  check(wrongShot === 0, 'the browser cuts the film at the same moments the reel does');

  // ------------------------------------------------------------------ 3. the same picture
  //
  // Exactly the same picture. Not "close enough", not "within a tolerance" — every pixel of every
  // frame, identical to the ones the native renderer wrote.
  //
  // That standard was not the one this test started with, and the story of how it got here is the
  // reason it is worth keeping. The first version allowed a step or two of difference, on the
  // reasoning that two compilers round arithmetic differently. It failed anyway: a tenth of the pixels
  // in a street scene disagreed, by up to 42 steps. Blurring did not absorb it, so it was not
  // sub-pixel. Turning the shadows off did not change it, so it was not the lighting. Cropping the
  // worst pixel and looking at both showed the same buildings STANDING IN DIFFERENT PLACES.
  //
  // The cause was two dice rolls inside one function call. C++ does not specify which argument is
  // evaluated first, and GCC and Clang really do choose differently, so the random numbers were dealt
  // out in a different order and the skyline came out different — for the same film, with the same
  // seed, depending only on which compiler built the renderer. One roll per statement fixed it, and
  // the two builds then agreed on all 881,280 pixels without a single step between them.
  //
  // So the tolerance stays at zero. Anything else here would have hidden that.
  var worst = 0;
  var worstFrame = '';
  var differing = 0;
  var samples = 0;

  manifest.frames.forEach(function (f) {
    var want = readPpm(path.join(FIXTURE_DIR, f.file));
    // Shutter 0, explicitly. Every fixture frame is a lone still and a still has no previous
    // camera to smear from, so the shutter could not fire here anyway — but saying so beats
    // relying on an absent argument becoming a zero.
    var ptr = render(f.time, want.width, want.height, manifest.supersample, manifest.shadows, 0);
    check(ptr !== 0, 'the module returns a frame for ' + f.file);
    if (!ptr) return;
    var got = Module.HEAPU8.subarray(ptr, ptr + want.width * want.height * 4);

    for (var i = 0, p = 0; i < want.width * want.height; i++, p += 3) {
      var d = 0;
      for (var c = 0; c < 3; c++) {
        var v = Math.abs(got[i * 4 + c] - want.rgb[p + c]);
        if (v > d) d = v;
      }
      if (d > 0) differing++;
      if (d > worst) { worst = d; worstFrame = f.file; }
    }
    samples++;
  });

  check(samples === manifest.frames.length, 'every fixture frame was rendered');
  check(worst === 0,
        'the browser draws exactly the film the command line draws — ' + differing +
        ' pixels differed, worst by ' + worst + (worstFrame ? ' in ' + worstFrame : ''));

  // ------------------------------------------------------------------ 4. it is a picture
  {
    var f = manifest.frames[manifest.frames.length - 1];
    var ptr = render(f.time, 320, 136, 1, 1, 0);
    check(ptr !== 0, 'a frame comes back at a size nobody asked for in the fixture');
    var px = Module.HEAPU8.subarray(ptr, ptr + 320 * 136 * 4);
    var seen = {};
    var lit = 0;
    for (var i = 0; i < 320 * 136; i++) {
      seen[px[i * 4] + ',' + px[i * 4 + 1] + ',' + px[i * 4 + 2]] = 1;
      if (px[i * 4] + px[i * 4 + 1] + px[i * 4 + 2] > 24) lit++;
    }
    check(Object.keys(seen).length > 40, 'a frame has a picture in it, not one flat colour');
    check(lit > 320 * 136 * 0.1, 'and enough of it is lit to see');
  }

  // ------------------------------------------------------------------ 5. it refuses the impossible
  check(render(0, 2, 2, 1, 1, 0) === 0, 'a frame smaller than a thumbnail is refused, not crashed on');
  check(load('nonsense') === 0, 'and a bad reel after a good one is still refused');
  check(render(0, 320, 136, 1, 1, 0) === 0, 'after which there is no film to render');
}

var factory = require(path.join(WASM_DIR, 'film3d.js'));
factory().then(function (Module) {
  try {
    run(Module);
  } catch (err) {
    failures.push('threw: ' + (err && err.stack ? err.stack : err));
  }
  if (failures.length) {
    failures.forEach(function (f) { console.log('FAIL: ' + f); });
    console.log(failures.length + ' failed of ' + checks);
    process.exit(1);
  }
  console.log('film 3d: all ' + checks + ' checks passed');
}).catch(function (err) {
  console.log('FAIL: the module would not start: ' + (err && err.stack ? err.stack : err));
  process.exit(1);
});
