#include "render/VulkanTexture.hpp"

#include "maz/core/Log.hpp"
#include "render/VulkanBuffer.hpp"
#include "render/VulkanContext.hpp"

#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_PNG
#define STBI_ONLY_JPEG
// stb_image is third-party and doesn't compile clean under our strict warning set; silence
// warnings for its include only — our own code below keeps the full checks.
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wshadow"
#pragma GCC diagnostic ignored "-Wpedantic"
#endif
#include <stb_image.h>
#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#endif

#include <algorithm>
#include <cmath>
#include <cstring>

namespace maz::render {

bool VulkanTexture::createFromFile(VulkanContext& ctx, const char* path) {
    int w = 0, h = 0, channels = 0;
    stbi_uc* pixels = stbi_load(path, &w, &h, &channels, STBI_rgb_alpha);
    if (!pixels) {
        MAZ_LOG_ERROR("stbi_load failed for '%s': %s", path, stbi_failure_reason());
        return false;
    }
    bool ok = create(ctx, static_cast<uint32_t>(w), static_cast<uint32_t>(h), pixels);
    stbi_image_free(pixels);
    return ok;
}


bool VulkanTexture::create(VulkanContext& ctx, uint32_t width, uint32_t height,
                           const void* rgba) {
    if (!ctx.valid() || width == 0 || height == 0 || rgba == nullptr) {
        return false;
    }
    m_width = width;
    m_height = height;
    // Full mip chain down to 1x1 (a single level for 1x1 textures).
    const uint32_t mipLevels =
        1u + static_cast<uint32_t>(std::floor(std::log2(static_cast<float>(std::max(width, height)))));
    const VkDeviceSize imageSize = static_cast<VkDeviceSize>(width) * height * 4;

    // 1. Staging buffer (host-visible), fill with pixels.
    VulkanBuffer staging;
    if (!staging.create(ctx, imageSize, VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
                        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                            VK_MEMORY_PROPERTY_HOST_COHERENT_BIT)) {
        return false;
    }
    if (void* dst = staging.map(ctx)) {
        std::memcpy(dst, rgba, static_cast<size_t>(imageSize));
    } else {
        staging.destroy(ctx);
        return false;
    }

    // 2. Device-local image.
    VkImageCreateInfo ii{};
    ii.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ii.imageType = VK_IMAGE_TYPE_2D;
    ii.format = VK_FORMAT_R8G8B8A8_SRGB;
    ii.extent = {width, height, 1};
    ii.mipLevels = mipLevels;
    ii.arrayLayers = 1;
    ii.samples = VK_SAMPLE_COUNT_1_BIT;
    ii.tiling = VK_IMAGE_TILING_OPTIMAL;
    // TRANSFER_SRC too: mip levels are generated by blitting each level from the previous one.
    ii.usage = VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT |
               VK_IMAGE_USAGE_SAMPLED_BIT;
    ii.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    ii.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(ctx.device(), &ii, nullptr, &m_image) != VK_SUCCESS) {
        MAZ_LOG_ERROR("vkCreateImage failed");
        staging.destroy(ctx);
        return false;
    }

    VkMemoryRequirements req{};
    vkGetImageMemoryRequirements(ctx.device(), m_image, &req);
    VkMemoryAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    ai.allocationSize = req.size;
    ai.memoryTypeIndex = findMemoryType(ctx, req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (ai.memoryTypeIndex == UINT32_MAX ||
        vkAllocateMemory(ctx.device(), &ai, nullptr, &m_memory) != VK_SUCCESS) {
        MAZ_LOG_ERROR("image memory allocation failed");
        staging.destroy(ctx);
        return false;
    }
    vkBindImageMemory(ctx.device(), m_image, m_memory, 0);

    // 3. Transition all levels UNDEFINED -> TRANSFER_DST, copy pixels into level 0, then blit-
    //    generate each successive mip level from the previous, leaving every level SHADER_READ.
    VkCommandBuffer cmd = ctx.beginSingleTimeCommands();

    VkImageMemoryBarrier barrier{};
    barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER;
    barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.image = m_image;
    barrier.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    barrier.subresourceRange.layerCount = 1;
    barrier.subresourceRange.levelCount = mipLevels;
    barrier.subresourceRange.baseMipLevel = 0;
    barrier.oldLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    barrier.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    barrier.srcAccessMask = 0;
    barrier.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0,
                         0, nullptr, 0, nullptr, 1, &barrier);

    VkBufferImageCopy copy{};
    copy.imageSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    copy.imageSubresource.layerCount = 1;
    copy.imageExtent = {width, height, 1};
    vkCmdCopyBufferToImage(cmd, staging.handle(), m_image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1,
                           &copy);

    // Blit-generate the mip chain. Each level is a linearly-downsampled copy of the previous one.
    barrier.subresourceRange.levelCount = 1;
    int32_t mipW = static_cast<int32_t>(width);
    int32_t mipH = static_cast<int32_t>(height);
    for (uint32_t i = 1; i < mipLevels; ++i) {
        // Previous level TRANSFER_DST -> TRANSFER_SRC so we can read it as the blit source.
        barrier.subresourceRange.baseMipLevel = i - 1;
        barrier.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
        barrier.newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
        barrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        barrier.dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, 0,
                             0, nullptr, 0, nullptr, 1, &barrier);

        const int32_t nextW = mipW > 1 ? mipW / 2 : 1;
        const int32_t nextH = mipH > 1 ? mipH / 2 : 1;
        VkImageBlit blit{};
        blit.srcOffsets[1] = {mipW, mipH, 1};
        blit.srcSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        blit.srcSubresource.mipLevel = i - 1;
        blit.srcSubresource.layerCount = 1;
        blit.dstOffsets[1] = {nextW, nextH, 1};
        blit.dstSubresource.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
        blit.dstSubresource.mipLevel = i;
        blit.dstSubresource.layerCount = 1;
        vkCmdBlitImage(cmd, m_image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, m_image,
                       VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &blit, VK_FILTER_LINEAR);

        // Previous level is done being read -> SHADER_READ.
        barrier.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
        barrier.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
        barrier.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                             VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, 0, 0, nullptr, 0, nullptr, 1,
                             &barrier);
        mipW = nextW;
        mipH = nextH;
    }

    // The last level is still TRANSFER_DST -> SHADER_READ.
    barrier.subresourceRange.baseMipLevel = mipLevels - 1;
    barrier.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    barrier.newLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
    barrier.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    barrier.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
                         0, 0, nullptr, 0, nullptr, 1, &barrier);

    ctx.endSingleTimeCommands(cmd);
    staging.destroy(ctx);

    // 4. View + sampler.
    VkImageViewCreateInfo vi{};
    vi.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vi.image = m_image;
    vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vi.format = VK_FORMAT_R8G8B8A8_SRGB;
    vi.subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT;
    vi.subresourceRange.levelCount = mipLevels;
    vi.subresourceRange.layerCount = 1;
    if (vkCreateImageView(ctx.device(), &vi, nullptr, &m_view) != VK_SUCCESS) {
        MAZ_LOG_ERROR("texture vkCreateImageView failed");
        return false;
    }

    VkSamplerCreateInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    si.magFilter = VK_FILTER_NEAREST; // crisp when magnified — keeps 2D/pixel-art and near 3D sharp
    si.minFilter = VK_FILTER_LINEAR;  // smooth when minified (distant 3D surfaces)
    // REPEAT so 3D meshes can tile a texture (UV > 1); 2D sprite UVs stay within [0,1] so this
    // is equivalent to clamp for them.
    si.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    si.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    si.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    // Trilinear mip sampling anti-aliases minified textures (the distant checker floor); mag stays
    // NEAREST so surfaces up close and the 2D UI keep their crisp look.
    si.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
    si.minLod = 0.0f;
    si.maxLod = static_cast<float>(mipLevels);
    if (vkCreateSampler(ctx.device(), &si, nullptr, &m_sampler) != VK_SUCCESS) {
        MAZ_LOG_ERROR("vkCreateSampler failed");
        return false;
    }
    return true;
}

void VulkanTexture::destroy(VulkanContext& ctx) {
    if (m_sampler) {
        vkDestroySampler(ctx.device(), m_sampler, nullptr);
        m_sampler = VK_NULL_HANDLE;
    }
    if (m_view) {
        vkDestroyImageView(ctx.device(), m_view, nullptr);
        m_view = VK_NULL_HANDLE;
    }
    if (m_image) {
        vkDestroyImage(ctx.device(), m_image, nullptr);
        m_image = VK_NULL_HANDLE;
    }
    if (m_memory) {
        vkFreeMemory(ctx.device(), m_memory, nullptr);
        m_memory = VK_NULL_HANDLE;
    }
}

} // namespace maz::render
